name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Compile TypeScript
        run: npm run compile
      
      - name: Build webview
        run: npm run build:webview
      
      - name: Run tests (if available)
        run: npm test --if-present
      
      - name: Package extension
        run: |
          npm install -g @vscode/vsce
          vsce package --no-dependencies
      
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-assistant-${{ matrix.node-version }}-${{ github.sha }}
          path: "*.vsix"
          retention-days: 30
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.node-version }}-${{ github.sha }}
          path: |
            out/
            !out/**/*.map
          retention-days: 7

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check TypeScript
        run: npx tsc --noEmit
      
      - name: Check Svelte components (if svelte-check is available)
        run: |
          if command -v npx svelte-check &> /dev/null; then
            npx svelte-check --workspace webviews
          else
            echo "svelte-check not available, skipping Svelte type checking"
          fi
