name: Publish to VS Code Marketplace

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0, leave empty to use package.json version)'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update version if specified
        if: github.event.inputs.version != ''
        run: |
          echo "Updating version to ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Build project
        run: npm run build

      - name: Install VSCE
        run: npm install -g @vscode/vsce
      
      - name: Verify package.json
        run: |
          echo "Checking package.json..."
          cat package.json | jq '.name, .version, .publisher'
      
      - name: Package extension
        run: vsce package --no-dependencies
      
      - name: List generated files
        run: ls -la *.vsix
      
      - name: Publish to VS Code Marketplace
        run: vsce publish -p $VSCE_TOKEN --no-dependencies
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      
      - name: Upload VSIX to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-assistant-release-${{ github.sha }}
          path: "*.vsix"
          retention-days: 90

  pre-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.version == ''
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Install VSCE
        run: npm install -g @vscode/vsce
      
      - name: Package pre-release
        run: vsce package --pre-release --no-dependencies
      
      - name: Publish pre-release to VS Code Marketplace
        run: vsce publish --pre-release -p $VSCE_TOKEN --no-dependencies
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      
      - name: Upload pre-release VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-assistant-prerelease-${{ github.sha }}
          path: "*.vsix"
          retention-days: 30
